FROM maven:3.8.4-openjdk-11-slim as build
WORKDIR /usr/src/app
COPY pom.xml /usr/src/app
COPY . .
RUN cd be-parent && \
    mvn clean package install -DskipTests && \
    cd .. && \
    cd be-common && \
    mvn clean package install -DskipTests && \
    cd .. && \
    mvn clean package && \
    mvn test || echo "Bypass Testing ^^!"
