name: Test, Build & Deploy Outsource Dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  unit-test-dev:
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3.0.1
      name: Checkout common modules
      with:
        repository: earable/be-parent
        path: be-parent
        token: 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
    - uses: actions/checkout@v3.0.1
      name: Checkout common modules
      with:
        repository: earable/be-common
        path: be-common
        token: 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
    - name: Build the Docker image
      run: |
        export APP_NAME="device-tracking-service"
        export GITHUB_SHORT_SHA="$(echo $GITHUB_SHA | cut -c1-8)"
        export APP_IMAGE_NAME="$GITLAB_REGISTRY/$APP_NAME:$GITHUB_REF_NAME-$GITHUB_SHORT_SHA"
        docker build -t $APP_IMAGE_NAME -f Dockerfile.test .
  build-docker-dev:
    needs: unit-test-dev
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-parent
        path: be-parent
        token: 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
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-common
        path: be-common
        token: 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
    - name: Build the Docker image
      run: |
        export APP_NAME="device-tracking-service"
        export GITHUB_SHORT_SHA="$(echo $GITHUB_SHA | cut -c1-8)"
        export APP_IMAGE_NAME="$GITLAB_REGISTRY/$APP_NAME:$GITHUB_REF_NAME-$GITHUB_SHORT_SHA"
        docker build -t $APP_IMAGE_NAME .
        docker push $APP_IMAGE_NAME
  deploy-k8s-dev:
    needs: build-docker-dev
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - name: Sync Commit to K8s Gitops
      run: |
        export APP_NAME="device-tracking-service"
        export VERSION="v1.0"
        curl --compressed -sS -H 'Connection: keep-alive' -u "${WEBHOOKD_BASIC_AUTH}" "${WEBHOOKD_URL}?application=${APP_NAME}&branch=${GITHUB_REF_NAME}&commit=${GITHUB_SHA}&version=${VERSION}"  &> /dev/stdout | tee -a /tmp/status
  post-test-dev:
    needs: deploy-k8s-dev
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - name: Run Post Test
      run: |
        sleep 30
        export HEALTHCHECK_URL="https://api-test.eardev.xyz/dts/api/v3/health"
        curl --compressed -sS -H 'Connection: keep-alive' "${HEALTHCHECK_URL}" &> /dev/stdout | tee -a /tmp/status
