name: Test, Build & Deploy Staging

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  unit-test-staging:
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-parent
        path: be-parent
        token: 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
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-common
        path: be-common
        token: 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
    - name: Build the Docker image
      run: |
        export APP_NAME="device-tracking-service"
        export GITHUB_SHORT_SHA="$(echo $GITHUB_SHA | cut -c1-8)"
        export APP_IMAGE_NAME="$GITLAB_REGISTRY/$APP_NAME:$GITHUB_REF_NAME-$GITHUB_SHORT_SHA"
        docker build -t $APP_IMAGE_NAME -f Dockerfile.test .
  build-docker-staging:
    needs: unit-test-staging
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-parent
        path: be-parent
        token: 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
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-common
        path: be-common
        token: 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
    - name: Build the Docker image
      run: |
        export APP_NAME="device-tracking-service"
        export GITHUB_SHORT_SHA="$(echo $GITHUB_SHA | cut -c1-8)"
        export APP_IMAGE_NAME="$GITLAB_REGISTRY/$APP_NAME:$GITHUB_REF_NAME-$GITHUB_SHORT_SHA"
        docker build -t $APP_IMAGE_NAME .
        docker push $APP_IMAGE_NAME
  deploy-k8s-staging:
    needs: build-docker-staging
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - name: Sync Commit to K8s Gitops
      run: |
        export APP_NAME="device-tracking-service"
        export VERSION="v1.0"
        curl --compressed -sS -H 'Connection: keep-alive' -u "${WEBHOOKD_BASIC_AUTH}" "${WEBHOOKD_URL}?application=${APP_NAME}&branch=${GITHUB_REF_NAME}&commit=${GITHUB_SHA}&version=${VERSION}"  &> /dev/stdout | tee -a /tmp/status
  post-test-staging:
    needs: deploy-k8s-staging
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - name: Run Post Test
      run: |
        sleep 30
        export HEALTHCHECK_URL="https://api.eardev.xyz/dts/api/v3/health"
        curl --compressed -sS -H 'Connection: keep-alive' "${HEALTHCHECK_URL}" &> /dev/stdout | tee -a /tmp/status
