name: Test Feature

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'feature/**' ]

jobs:

  build-test-feature:
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-parent
        path: be-parent
        token: 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
    - uses: actions/checkout@v3
      name: Checkout common modules
      with:
        repository: earable/be-common
        path: be-common
        token: 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
    - name: Build the Docker image
      run: |
        export APP_NAME="device-tracking-service"
        docker build -f Dockerfile.test .
